# Generated by Django 3.0.8 on 2020-07-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='url', max_length=200),
        ),
    ]
